<a href="https://colab.research.google.com/github/GITSangWoo/BigDataTest/blob/main/%EB%B9%85%EB%B6%84%EA%B8%B0%EC%8B%A4%EC%A0%841(%EC%A0%84%EC%B2%98%EB%A6%AC%EC%98%88%EC%A0%9C).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#작업형 1유형

##문제1

In [ ]:

import pandas as pd
import numpy as np

df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/데이터 셋/P210201.csv")
print(df.iloc[380])

Unnamed: 0    381.0000
crim           88.9762
zn              0.0000
indus          18.1000
chas            0.0000
nox             0.6710
rm              6.9680
age            91.9000
dis             1.4165
rad            24.0000
tax           666.0000
ptratio        20.2000
b             396.9000
lstat          17.2100
medv           10.4000
Name: 380, dtype: float64

In [ ]:
#crim 항목에서 상위에서 10번째 값구하기
top10 = df['crim'].sort_values(ascending=False).head(10)
print(top10)

tenth = top10.iloc[9]
print(tenth)

380    88.9762
418    73.5341
405    67.9208
410    51.1358
414    45.7461
404    41.5292
398    38.3518
427    37.6619
413    28.6558
417    25.9406
Name: crim, dtype: float64
25.9406

In [ ]:
#10번째 값으로 상위 10개의 값을 변환
df['crim']=np.where(df['crim']>=tenth,tenth,df['crim'])

#age가 80이상인 값
age80=df[df['age']>=80]
print(age80['age'].describe())

#crim 평균을 구하기
print(round(age80['crim'].mean(),2))

count    240.000000
mean      93.230833
std        5.734098
min       80.300000
25%       88.750000
50%       94.500000
75%       98.200000
max      100.000000
Name: age, dtype: float64
5.76

##문제2

In [ ]:
import pandas as pd
import numpy as np
housing=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/데이터 셋/P210202.csv")

#첫 번째 행부터 순서대로 80%까지의 데이터를 훈련 데이터로 추출
df=housing.iloc[:int(len(housing)*0.8),]
df=pd.DataFrame(df)

In [ ]:
#대체전의 표준편차
a=df['total_bedrooms'].std()

#total_bedroom 변수의 결측치를 중앙값으로 대체
median_train =df['total_bedrooms'].median()
df['total_bedrooms']=df['total_bedrooms'].fillna(median_train)

#대체후의 표준편차
b=df['total_bedrooms'].std()

#대체전과 대체후의 표준편차값의 차이의 절대값을 소수 둘째짜리 까지만 계산
print(round(np.abs(a-b),2))

1.98

##문제3

In [ ]:
#데이터 불러오기
import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/데이터 셋/P210203.csv")
print(df)

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [ ]:
#이상치 구하기 (이상치 기준은 평균으로부터 1.5표준편차 만큼 떨어진 값)
upper=df['charges'].mean()+1.5*np.std(df['charges'])
lower=df['charges'].mean()-1.5*np.std(df['charges'])

#이상치들의 합 구하기
result = df[(df['charges']>=upper) | (df['charges']<=lower)]['charges'].sum()

#정수부분만출력
print(int(result))

6421430

##문제4

In [ ]:
import pandas as pd
import numpy as np

housing=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/데이터 셋/P210301.csv")
print(housing.info)

<bound method DataFrame.info of        longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0
1        -122.22     37.86                21.0       7099.0          1106.0
2        -122.24     37.85                52.0       1467.0           190.0
3        -122.25     37.85                52.0       1274.0           235.0
4        -122.25     37.85                52.0       1627.0           280.0
...          ...       ...                 ...          ...             ...
20635    -121.09     39.48                25.0       1665.0           374.0
20636    -121.21     39.49                18.0        697.0           150.0
20637    -121.22     39.43                17.0       2254.0           485.0
20638    -121.32     39.43                18.0       1860.0           409.0
20639    -121.24     39.37                16.0       2785.0           616.0

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0
1          2401.0      1138.0         8.3014            358500.0
2           496.0       177.0         7.2574            352100.0
3           558.0       219.0         5.6431            341300.0
4           565.0       259.0         3.8462            342200.0
...           ...         ...            ...                 ...
20635       845.0       330.0         1.5603             78100.0
20636       356.0       114.0         2.5568             77100.0
20637      1007.0       433.0         1.7000             92300.0
20638       741.0       349.0         1.8672             84700.0
20639      1387.0       530.0         2.3886             89400.0

      ocean_proximity
0            NEAR BAY
1            NEAR BAY
2            NEAR BAY
3            NEAR BAY
4            NEAR BAY
...               ...
20635          INLAND
20636          INLAND
20637          INLAND
20638          INLAND
20639          INLAND

[20640 rows x 10 columns]>

In [ ]:
#housing 데이터 세트에서 결측값이 있는 모든 행을 제거
print(sum(housing.isnull().sum()))
print(sum(housing.isnull().any(axis=1)))


housing=housing.dropna()

print(sum(housing.isnull().any(axis=1)))

207
207
0

In [ ]:
#데이터의 순서대로 상위 70%의 데이터를 학습 데이터로 만들고
df=housing.iloc[:int(len(df)*0.7),:]
print(df)

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0
1        -122.22     37.86                21.0       7099.0          1106.0
2        -122.24     37.85                52.0       1467.0           190.0
3        -122.25     37.85                52.0       1274.0           235.0
4        -122.25     37.85                52.0       1627.0           280.0
...          ...       ...                 ...          ...             ...
14436    -117.24     32.80                28.0       1072.0           331.0
14437    -117.24     32.80                18.0       2205.0           661.0
14438    -117.24     32.80                19.0       1863.0           497.0
14439    -117.24     32.80                30.0       1917.0           462.0
14440    -117.24     32.80                29.0       3376.0           882.0

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0
1          2401.0      1138.0         8.3014            358500.0
2           496.0       177.0         7.2574            352100.0
3           558.0       219.0         5.6431            341300.0
4           565.0       259.0         3.8462            342200.0
...           ...         ...            ...                 ...
14436       692.0       321.0         2.1357            187500.0
14437       874.0       580.0         3.8018            112500.0
14438       868.0       503.0         2.2880            210000.0
14439       828.0       437.0         2.4671            276300.0
14440      1513.0       843.0         3.1010            238200.0

      ocean_proximity
0            NEAR BAY
1            NEAR BAY
2            NEAR BAY
3            NEAR BAY
4            NEAR BAY
...               ...
14436      NEAR OCEAN
14437      NEAR OCEAN
14438      NEAR OCEAN
14439      NEAR OCEAN
14440      NEAR OCEAN

[14303 rows x 10 columns]

In [ ]:
print(int(np.quantile(df["housing_median_age"],q=0.25)))

19

##문제5

In [ ]:
import pandas as pd

ti_data=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/데이터 셋/P210302.csv")


cs = ti_data.isna().sum()/len(ti_data)
cs = pd.DataFrame(cs)
ds= cs.sort_values(by=0,ascending=False)
print(ds)
print(ds.index[0])

                    0
Age          0.198653
Embarked     0.002245
PassengerId  0.000000
Survived     0.000000
Pclass       0.000000
Name         0.000000
Sex          0.000000
SibSp        0.000000
Parch        0.000000
Ticket       0.000000
Fare         0.000000
Age

##문제6

In [ ]:
import pandas as pd

df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/데이터 셋/P210303.csv")
df

,country,iso2,iso3,iso_numeric,g_whoregion,year,new_sp,new_sn,new_su,new_ep,...,hiv_elig_all_tpt,hiv_elig_all,hiv_elig_new_tpt,hiv_elig_new,hiv_all_tpt,hiv_all,hiv_new_tpt,hiv_new,hiv_all_tpt_completed,hiv_all_tpt_started
0,Afghanistan,AF,AFG,4,EMR,1980,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AF,AFG,4,EMR,1981,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,AF,AFG,4,EMR,1982,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,AF,AFG,4,EMR,1983,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,AF,AFG,4,EMR,1984,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8702,Zimbabwe,ZW,ZWE,716,AFR,2016,NaN,NaN,NaN,2915.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8703,Zimbabwe,ZW,ZWE,716,AFR,2017,NaN,NaN,NaN,2657.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8704,Zimbabwe,ZW,ZWE,716,AFR,2018,NaN,NaN,NaN,2547.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8705,Zimbabwe,ZW,ZWE,716,AFR,2019,NaN,NaN,NaN,1957.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8706,Zimbabwe,ZW,ZWE,716,AFR,2020,NaN,NaN,NaN,1140.0,...,156512.0,495655.0,39661.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#country,year,new_sp 컬럼에 결측값이 있을 경우 제거
df=df[['country','year','new_sp']]
df=df.dropna()

# 2000년도에 국가별 결핵 발생 건수에 대한 평균 결핵 발생 건수를 구하기

df2000=df[df['year']==2000]
mdf2000=df2000['new_sp'].mean()
mdf2000

7865.341836734694

In [ ]:
#2000년도 결핵 발생건수가 2000년도 국가별 결핵발생 건수에 대한 평균 결핵 발생 건수보다 결핵 발생 건수가 높은 국가의 개수를 구하라
print(len(df2000[df2000['new_sp']>=mdf2000]))

38

##문제7

In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/데이터 셋/P220401.csv")
df

    x   y
0   1  86
1   2  91
2   3  15
3   4  50
4   5  78
5   6  34
6   7  37
7   8  56
8   9  64
9  10  74

In [ ]:
#(1) y 변수의 1 사분위와 3사분위 값을 구하시오.
quantile_1=np.quantile(df['y'],q=0.25)
print(quantile_1)
quantile_3=np.quantile(df['y'],q=0.75)
print(quantile_3)

40.25
77.0

In [ ]:
print(quantile_3-quantile_1)

36.75

In [ ]:
print(int(quantile_3-quantile_1))

36

In [ ]:
q1=df['y'].quantile(0.25)
q3=df['y'].quantile(0.75)
print(int(q3-q1))

36
count    10.000000
mean     58.500000
std      24.712795
min      15.000000
25%      40.250000
50%      60.000000
75%      77.000000
max      91.000000
Name: y, dtype: float64

##문제8

In [ ]:
import pandas as pd

facebook=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/데이터 셋/P220402.csv")

facebook['positive_ratio']=(facebook['num_loves']+facebook['num_wows'])/facebook['num_reactions']
facebook_video=facebook[facebook['status_type']=='video']
facebook_video

,status_id,status_type,status_published,num_reactions,num_comments,num_shares,num_likes,num_loves,num_wows,num_hahas,num_sads,num_angrys,positive_ratio
0,1,video,4/22/2018 6:00,529,512,262,432,92,3,1,1,0,0.179584
2,3,video,4/21/2018 6:17,227,236,57,204,21,1,1,0,0,0.096916
6,7,video,4/18/2018 0:24,503,614,72,418,70,10,2,0,3,0.159046
7,8,video,4/17/2018 7:42,295,453,53,260,32,1,1,0,1,0.111864
15,16,video,4/1/2018 5:16,332,100,30,303,23,1,5,0,0,0.072289
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6974,6975,video,7/17/2017 8:01,300,5404,219,245,44,1,7,2,1,0.150000
6977,6978,video,7/15/2017 10:52,253,4432,167,209,29,5,5,5,0,0.134387
6978,6979,video,7/15/2017 4:42,324,4472,232,278,33,5,5,3,0,0.117284
6992,6993,video,3/3/2017 9:39,36,240,20,33,2,1,0,0,0,0.083333
7034,7035,video,10/10/2016 1:07,6,0,0,6,0,0,0,0,0,0.000000

In [ ]:
print(len(facebook_video[(facebook_video['positive_ratio']>0.4) & (facebook['positive_ratio']<0.5)]))

90

<ipython-input-152-c6fbbfac6871>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(len(facebook_video[(facebook_video['positive_ratio']>0.4) & (facebook['positive_ratio']<0.5)]))

##문제9

In [ ]:
import pandas as pd

net=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/데이터 셋/P220403.csv")
net

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [ ]:
print(net['date_added'].head())

0    September 25, 2021
1    September 24, 2021
2    September 24, 2021
3    September 24, 2021
4    September 24, 2021
Name: date_added, dtype: object

In [ ]:
net['date_added']=pd.to_datetime(net['date_added'],format = "%B %d, %Y")
print(net['date_added'].head())
result=net[(net['country']=='United Kingdom')&
           (net['date_added'].dt.year==2018)&
           (net['date_added'].dt.month==1)]
result
print(len(result))

0   2021-09-25
1   2021-09-24
2   2021-09-24
3   2021-09-24
4   2021-09-24
Name: date_added, dtype: datetime64[ns]
6

##문제10

In [ ]:
import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/데이터 셋/P220501.csv",encoding='euc-kr')
df

,시도명,시군구명,종량제봉투종류,종량제봉투처리방식,종량제봉투용도,종량제봉투사용대상,1L가격,1.5L가격,2L가격,2.5L가격,3L가격,5L가격,10L가격,20L가격,30L가격,50L가격,60L가격,75L가격,100L가격,120L가격,125L가격,관리부서명,관리부서전화번호,데이터기준일자,제공기관코드,제공기관명
0,경기도,안양시,규격봉투,매립용,생활쓰레기,사업장용,0,0,0,0,0,150,300,550,0,1400,0,2100,0,0,0,자원순환과,031-8045-5448,2022-08-12,3830000,경기도 안양시
1,경기도,안양시,규격봉투,매립용,생활쓰레기,기타,0,0,0,0,0,150,300,550,0,1400,0,2100,0,0,0,자원순환과,031-8045-5448,2022-08-12,3830000,경기도 안양시
2,경기도,안양시,규격봉투,소각용,음식물쓰레기,가정용,0,50,0,80,0,150,300,550,0,0,0,0,0,0,0,자원순환과,031-8045-5448,2022-08-12,3830000,경기도 안양시
3,경기도,안양시,규격봉투,소각용,음식물쓰레기,사업장용,0,50,0,80,0,150,300,550,0,0,0,0,0,0,0,자원순환과,031-8045-5448,2022-08-12,3830000,경기도 안양시
4,경기도,안양시,규격봉투,소각용,음식물쓰레기,기타,0,50,0,80,0,150,300,550,0,0,0,0,0,0,0,자원순환과,031-8045-5448,2022-08-12,3830000,경기도 안양시
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
741,충청남도,계룡시,재사용규격봉투,소각용,생활쓰레기,가정용,0,0,0,0,0,120,240,470,0,1170,0,0,2320,0,0,환경위생과,042-840-2484,2019-05-16,5580000,충청남도 계룡시
742,충청남도,계룡시,재사용규격봉투,소각용,생활쓰레기,사업장용,0,0,0,0,0,120,240,470,0,1170,0,0,2320,0,0,환경위생과,042-840-2484,2019-05-16,5580000,충청남도 계룡시
743,전라북도,김제시,규격봉투,소각용,생활쓰레기,가정용,0,0,0,0,0,100,190,360,0,890,0,0,0,0,0,환경과,063-540-3165,2018-08-09,4710000,전라북도 김제시
744,전라북도,김제시,특수규격마대,매립용,생활쓰레기,가정용,0,0,0,0,0,0,0,360,0,890,0,0,0,0,0,환경과,063-540-3165,2018-08-09,4710000,전라북도 김제시
745,전라북도,김제시,김장용봉투,소각용,음식물쓰레기,가정용,0,0,0,0,0,0,0,470,0,1150,0,0,0,0,0,환경과,063-540-3165,2018-08-09,4710000,전라북도 김제시

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 746 entries, 0 to 745
Data columns (total 26 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   시도명        746 non-null    object
 1   시군구명       746 non-null    object
 2   종량제봉투종류    746 non-null    object
 3   종량제봉투처리방식  746 non-null    object
 4   종량제봉투용도    746 non-null    object
 5   종량제봉투사용대상  746 non-null    object
 6   1L가격       746 non-null    int64
 7   1.5L가격     746 non-null    int64
 8   2L가격       746 non-null    int64
 9   2.5L가격     746 non-null    int64
 10  3L가격       746 non-null    int64
 11  5L가격       746 non-null    int64
 12  10L가격      746 non-null    int64
 13  20L가격      746 non-null    int64
 14  30L가격      746 non-null    int64
 15  50L가격      746 non-null    int64
 16  60L가격      746 non-null    int64
 17  75L가격      746 non-null    int64
 18  100L가격     746 non-null    int64
 19  120L가격     746 non-null    int64
 20  125L가격     746 non-null    int64
 21  관리부서명      746 non-null    object
 22  관리부서전화번호   746 non-null    object
 23  데이터기준일자    746 non-null    object
 24  제공기관코드     746 non-null    object
 25  제공기관명      746 non-null    object
dtypes: int64(15), object(11)
memory usage: 151.7+ KB
None

In [ ]:
trash=df[(df['종량제봉투종류']=='규격봉투') &(df['종량제봉투용도']=='음식물쓰레기')&(df['2L가격'] !=  0)]
print(int(trash['2L가격'].mean()))

120

##문제11

In [ ]:
import pandas as pd

body=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/데이터 셋/P220502.csv")

body['BMI']=body['Weight']/((body['Height']*0.01)**2)
body

     Gender  Height  Weight  Index        BMI
0      Male     174      96      4  31.708284
1      Male     189      87      2  24.355421
2    Female     185     110      4  32.140248
3    Female     195     104      3  27.350427
4      Male     149      61      3  27.476240
..      ...     ...     ...    ...        ...
495  Female     150     153      5  68.000000
496  Female     184     121      4  35.739603
497  Female     141     136      5  68.407022
498    Male     150      95      5  42.222222
499    Male     173     131      5  43.770256

[500 rows x 5 columns]

In [ ]:
bmi_normal = body[(body['BMI']>=18.5) & (body['BMI']<23)]
bmi_warning = body[(body['BMI']>=23) & (body['BMI']<25)]

print(abs(len(bmi_normal)-len(bmi_warning)))

28

##문제12

In [ ]:
import pandas as pd

df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/데이터 셋/P220503.csv",encoding="euc-kr")
df

,시도교육청,지역교육청,지역,정보공시 학교코드,학교명,학교급코드,설립구분,제외여부,제외사유,1학년 전입학생수,...,4학년 전체학생수,5학년 전입학생수,5학년 전출학생수,5학년 전체학생수,6학년 전입학생수,6학년 전출학생수,6학년 전체 학생수,전입학생수(계),전출학생수(계),전체학생수(계)
0,서울특별시교육청,교육부,서울특별시 서초구,S000003511,서울교육대학교부설초등학교,2,국립,N,NaN,1,...,103,0,1,112,0,1,105,2,5,616
1,서울특별시교육청,교육부,서울특별시 종로구,S000003563,서울대학교사범대학부설초등학교,2,국립,N,NaN,1,...,105,3,5,109,1,0,110,21,18,632
2,서울특별시교육청,서울특별시강남서초교육지원청,서울특별시 강남구,S010000738,서울개일초등학교,2,공립,N,NaN,18,...,123,46,4,136,41,6,170,232,36,837
3,서울특별시교육청,서울특별시강남서초교육지원청,서울특별시 강남구,S010000741,서울구룡초등학교,2,공립,N,NaN,5,...,74,9,3,85,7,2,86,49,14,492
4,서울특별시교육청,서울특별시강남서초교육지원청,서울특별시 강남구,S010000742,서울논현초등학교,2,공립,N,NaN,1,...,54,4,4,65,4,1,52,14,26,339
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6282,제주특별자치도교육청,제주시교육지원청,제주특별자치도 제주시,S170000801,월랑초등학교,2,공립,N,NaN,0,...,112,4,3,124,1,2,148,19,26,777
6283,제주특별자치도교육청,제주시교육지원청,제주특별자치도 제주시,S170000834,이도초등학교,2,공립,N,NaN,2,...,182,9,13,208,3,3,184,40,53,1233
6284,제주특별자치도교육청,제주시교육지원청,제주특별자치도 제주시,S170000836,도련초등학교,2,공립,N,NaN,11,...,147,9,2,133,4,0,93,68,16,985
6285,제주특별자치도교육청,제주시교육지원청,제주특별자치도 제주시,S170000837,삼화초등학교,2,공립,N,NaN,2,...,165,8,11,155,1,3,131,37,45,862
6286,제주특별자치도교육청,제주시교육지원청,제주특별자치도 제주시,S170000839,하귀일초등학교,2,공립,N,NaN,10,...,118,5,9,87,3,10,92,50,49,603

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6287 entries, 0 to 6286
Data columns (total 30 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   시도교육청       6287 non-null   object
 1   지역교육청       6287 non-null   object
 2   지역          6280 non-null   object
 3   정보공시 학교코드   6287 non-null   object
 4   학교명         6287 non-null   object
 5   학교급코드       6287 non-null   int64
 6   설립구분        6287 non-null   object
 7   제외여부        6287 non-null   object
 8   제외사유        0 non-null      float64
 9   1학년 전입학생수   6287 non-null   int64
 10  1학년 전출학생수   6287 non-null   int64
 11  1학년 전체학생수   6287 non-null   int64
 12  2학년 전입학생수   6287 non-null   int64
 13  2학년 전출학생수   6287 non-null   int64
 14  2학년 전체학생수   6287 non-null   int64
 15  3학년 전입학생수   6287 non-null   int64
 16  3학년 전출학생수   6287 non-null   int64
 17  3학년 전체학생수   6287 non-null   int64
 18  4학년 전입학생수   6287 non-null   int64
 19  4학년 전출학생수   6287 non-null   int64
 20  4학년 전체학생수   6287 non-null   int64
 21  5학년 전입학생수   6287 non-null   int64
 22  5학년 전출학생수   6287 non-null   int64
 23  5학년 전체학생수   6287 non-null   int64
 24  6학년 전입학생수   6287 non-null   int64
 25  6학년 전출학생수   6287 non-null   int64
 26  6학년 전체 학생수  6287 non-null   int64
 27  전입학생수(계)    6287 non-null   int64
 28  전출학생수(계)    6287 non-null   int64
 29  전체학생수(계)    6287 non-null   int64
dtypes: float64(1), int64(22), object(7)
memory usage: 1.4+ MB
None

In [ ]:
df['순전입학생수']=df['전입학생수(계)']-df['전출학생수(계)']
df=df.sort_values(by='순전입학생수',ascending=False)

In [ ]:
print(df['전체학생수(계)'].iloc[0])

956
시도교육청             강원도교육청
지역교육청         강원도원주교육지원청
지역               강원도 원주시
정보공시 학교코드     S100003975
학교명               섬강초등학교
학교급코드                  2
설립구분                  공립
제외여부                   N
제외사유                 NaN
1학년 전입학생수             83
1학년 전출학생수              7
1학년 전체학생수            240
2학년 전입학생수            271
2학년 전출학생수              4
2학년 전체학생수            179
3학년 전입학생수            255
3학년 전출학생수              2
3학년 전체학생수            165
4학년 전입학생수            222
4학년 전출학생수              6
4학년 전체학생수            139
5학년 전입학생수            204
5학년 전출학생수              3
5학년 전체학생수            123
6학년 전입학생수            152
6학년 전출학생수              2
6학년 전체 학생수           110
전입학생수(계)            1187
전출학생수(계)              24
전체학생수(계)             956
순전입학생수              1163
Name: 3563, dtype: object

##문제13

In [ ]:
import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/데이터 셋/P230601.csv")
df

                   신고일시              출동일시    출동소방서
0      2018-01-02 11:45  2018-01-02 11:50    양평소방서
1      2018-01-04 01:56  2018-01-04 02:00  수원남부소방서
2      2018-01-05 16:54  2018-01-05 16:54    김포소방서
3      2018-01-07 00:56  2018-01-07 01:01    포천소방서
4      2018-01-05 16:54  2018-01-05 16:55    고양소방서
...                 ...               ...      ...
21537  2018-12-16 12:00  2018-12-16 12:03  수원남부소방서
21538  2018-12-18 09:20  2018-12-18 09:22    안산소방서
21539  2018-12-14 13:03  2018-12-14 13:05    분당소방서
21540  2018-12-15 17:49  2018-12-15 17:56    김포소방서
21541  2018-12-15 21:54  2018-12-15 21:56    하남소방서

[21542 rows x 3 columns]

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21542 entries, 0 to 21541
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   신고일시    21542 non-null  object
 1   출동일시    21542 non-null  object
 2   출동소방서   21542 non-null  object
dtypes: object(3)
memory usage: 505.0+ KB
None

In [ ]:
df['calltime']=pd.to_datetime(df['신고일시'])
df['arrivetime']=pd.to_datetime(df['출동일시'])
df['fire_station']=df['출동소방서']
df['diff']=(df['arrivetime']-df['calltime']).dt.total_seconds()

print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21542 entries, 0 to 21541
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   신고일시          21542 non-null  object
 1   출동일시          21542 non-null  object
 2   출동소방서         21542 non-null  object
 3   calltime      21542 non-null  datetime64[ns]
 4   arrivetime    21542 non-null  datetime64[ns]
 5   fire_station  21542 non-null  object
 6   diff          21542 non-null  float64
dtypes: datetime64[ns](2), float64(1), object(4)
memory usage: 1.2+ MB
None

In [ ]:
df =df.groupby([df['fire_station'],df['calltime'].dt.year,df['calltime'].dt.month]).mean('diff')

In [ ]:
df=df.sort_values('diff',ascending=False)
df

                                  diff
fire_station calltime calltime
대화119안전센터    2018     9         3840.0
초월119안전센터    2018     7         2925.0
                      6         2865.0
경기도소방재난본부    2018     8         2220.0
                      10        1620.0
...                                ...
용문119안전센터    2018     2           45.0
설악119안전센터    2018     6           45.0
백암119안전센터    2018     12          40.0
영북119안전센터    2018     3            0.0
가평119안전센터    2018     6            0.0

[623 rows x 1 columns]

In [ ]:
print(round(df['diff'].iloc[0]/60))

64

##문제14

In [ ]:
import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/데이터 셋/P230602.csv")
df

,school_name,student_1,student_2,student_3,student_4,student_5,student_6,teacher
0,서울교육대학교부설초등학교,95,95,95,104,108,110,31
1,서울대학교사범대학부설초등학교,97,100,102,102,102,104,36
2,서울개일초등학교,183,163,176,186,177,193,42
3,서울구룡초등학교,109,115,115,131,133,132,38
4,서울논현초등학교,34,47,34,46,46,46,18
...,...,...,...,...,...,...,...,...
6304,월랑초등학교,77,91,103,127,127,135,32
6305,이도초등학교,199,174,186,228,192,214,50
6306,도련초등학교,199,221,198,211,195,179,54
6307,삼화초등학교,111,104,124,136,141,128,34
6308,하귀일초등학교,100,99,103,119,94,97,30

In [ ]:
df["tch_std"]=(df['student_1']+df['student_2']+df['student_3']+df['student_4']+df['student_5']+df['student_6'])/df['teacher']
df=df.sort_values('tch_std',ascending=False)
df

,school_name,student_1,student_2,student_3,student_4,student_5,student_6,teacher,tch_std
1044,대구삼육초등학교,36,39,40,39,37,28,6,36.500000
3387,원주삼육초등학교,84,90,90,90,96,96,16,34.125000
1464,광주삼육초등학교,90,96,96,96,102,102,18,32.333333
360,태강삼육초등학교,129,128,128,128,128,128,24,32.041667
687,동성초등학교,128,128,128,128,127,89,23,31.652174
...,...,...,...,...,...,...,...,...,...
4180,청파초등학교외연도분교장,0,1,2,0,1,1,5,1.000000
2778,포천삼정초등학교,0,0,0,2,1,2,7,0.714286
5122,흑산초등학교홍도분교장,0,0,0,0,1,0,2,0.500000
6032,산양초등학교곤리분교장,0,0,0,1,0,0,2,0.500000
3403,기린초등학교방동분교장,0,0,0,0,0,0,0,NaN

In [ ]:
print(int(df['teacher'].iloc[0]))
print((df['teacher'].loc[0]))

6
31

##문제15

In [ ]:
import pandas as pd

crim=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/데이터 셋/P230603.csv")
crim

         년월  강력범   절도범   폭력범   지능범  풍속범  기타형사범
0   2007-01  291  2608  6494  5283  242   1126
1   2007-02  252  2403  4613  4270  158    880
2   2007-03  292  2273  6242  5110  196   1119
3   2007-04  306  2794  6813  5492  250   1311
4   2007-05  298  3469  7221  5432  192   1412
..      ...  ...   ...   ...   ...  ...    ...
79  2013-08  615  5650  5796  6345  120   1764
80  2013-09  547  5602  5603  6126  139   1693
81  2013-01  669  5690  6016  6762  166   2099
82  2013-11  415  4702  5367  6962  115   1988
83  2013-12  472  4616  5219  6505  106   1656

[84 rows x 7 columns]

In [ ]:
print(crim.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84 entries, 0 to 83
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   년월      84 non-null     object
 1   강력범     84 non-null     int64
 2   절도범     84 non-null     int64
 3   폭력범     84 non-null     int64
 4   지능범     84 non-null     int64
 5   풍속범     84 non-null     int64
 6   기타형사범   84 non-null     int64
dtypes: int64(6), object(1)
memory usage: 4.7+ KB
None

In [ ]:
crim['date']=pd.to_datetime(crim['년월'],format=("%Y-%m"))
crim['total_crime']=crim['강력범']+crim['절도범']+crim['폭력범']+crim['지능범']+crim['풍속범']+crim['기타형사범']
crim

         년월  강력범   절도범   폭력범   지능범  풍속범  기타형사범       date  total_crime
0   2007-01  291  2608  6494  5283  242   1126 2007-01-01        16044
1   2007-02  252  2403  4613  4270  158    880 2007-02-01        12576
2   2007-03  292  2273  6242  5110  196   1119 2007-03-01        15232
3   2007-04  306  2794  6813  5492  250   1311 2007-04-01        16966
4   2007-05  298  3469  7221  5432  192   1412 2007-05-01        18024
..      ...  ...   ...   ...   ...  ...    ...        ...          ...
79  2013-08  615  5650  5796  6345  120   1764 2013-08-01        20290
80  2013-09  547  5602  5603  6126  139   1693 2013-09-01        19710
81  2013-01  669  5690  6016  6762  166   2099 2013-01-01        21402
82  2013-11  415  4702  5367  6962  115   1988 2013-11-01        19549
83  2013-12  472  4616  5219  6505  106   1656 2013-12-01        18574

[84 rows x 9 columns]

In [ ]:
crim=crim.groupby(crim['date'].dt.year).mean('total_crime').sort_values("total_crime",ascending=False)

In [ ]:
crim

,강력범,절도범,폭력범,지능범,풍속범,기타형사범,total_crime
date,,,,,,,
2013,523.000000,5132.083333,5451.833333,6378.416667,130.166667,1713.750000,19329.250000
2012,501.916667,5110.750000,5885.250000,6019.833333,161.833333,1612.083333,19291.666667
2011,575.416667,4524.500000,6003.666667,5937.666667,198.083333,1373.666667,18613.000000
2009,374.583333,3097.916667,6089.083333,6021.833333,516.916667,1405.333333,17505.666667
2010,552.333333,4115.166667,5733.166667,5530.666667,204.750000,1254.916667,17391.000000
2008,314.833333,2408.333333,6190.833333,5179.083333,248.333333,1290.416667,15631.833333
2007,281.916667,2498.083333,6168.333333,4545.916667,196.583333,1189.500000,14880.333333

In [ ]:
print(round(crim['total_crime'].iloc[0]))

19329

#작업형 2유형

In [ ]:
import pandas as pd

train=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/데이터 셋/P210204-01.csv")
test=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/데이터 셋/P210204-02.csv")

print(train.info())
print(test.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8009 entries, 0 to 8008
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   8009 non-null   int64
 1   Warehouse_block      8009 non-null   object
 2   Mode_of_Shipment     8009 non-null   object
 3   Customer_care_calls  8009 non-null   int64
 4   Customer_rating      8009 non-null   int64
 5   Cost_of_the_Product  8009 non-null   int64
 6   Prior_purchases      8009 non-null   int64
 7   Product_importance   8009 non-null   object
 8   Gender               8009 non-null   object
 9   Discount_offered     8009 non-null   int64
 10  Weight_in_gms        8009 non-null   int64
 11  Reached.on.Time_Y.N  8009 non-null   int64
dtypes: int64(8), object(4)
memory usage: 751.0+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2990 entries, 0 to 2989
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   2990 non-null   int64
 1   Warehouse_block      2990 non-null   object
 2   Mode_of_Shipment     2990 non-null   object
 3   Customer_care_calls  2990 non-null   int64
 4   Customer_rating      2990 non-null   int64
 5   Cost_of_the_Product  2990 non-null   int64
 6   Prior_purchases      2990 non-null   int64
 7   Product_importance   2990 non-null   object
 8   Gender               2990 non-null   object
 9   Discount_offered     2990 non-null   int64
 10  Weight_in_gms        2990 non-null   int64
dtypes: int64(7), object(4)
memory usage: 257.1+ KB
None

In [ ]:
#데이터 전처리

#ID저장 및 제거
train_ID=train.iloc[:,0]
test_ID=test.iloc[:,0]
#print(train_ID)
#print(test_ID)
train=train.drop('ID',axis=1)
test=test.drop('ID',axis=1)
#print(train.info())
#print(test.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8009 entries, 0 to 8008
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Warehouse_block      8009 non-null   object
 1   Mode_of_Shipment     8009 non-null   object
 2   Customer_care_calls  8009 non-null   int64
 3   Customer_rating      8009 non-null   int64
 4   Cost_of_the_Product  8009 non-null   int64
 5   Prior_purchases      8009 non-null   int64
 6   Product_importance   8009 non-null   object
 7   Gender               8009 non-null   object
 8   Discount_offered     8009 non-null   int64
 9   Weight_in_gms        8009 non-null   int64
 10  Reached.on.Time_Y.N  8009 non-null   int64
dtypes: int64(7), object(4)
memory usage: 688.4+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2990 entries, 0 to 2989
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Warehouse_block      2990 non-null   object
 1   Mode_of_Shipment     2990 non-null   object
 2   Customer_care_calls  2990 non-null   int64
 3   Customer_rating      2990 non-null   int64
 4   Cost_of_the_Product  2990 non-null   int64
 5   Prior_purchases      2990 non-null   int64
 6   Product_importance   2990 non-null   object
 7   Gender               2990 non-null   object
 8   Discount_offered     2990 non-null   int64
 9   Weight_in_gms        2990 non-null   int64
dtypes: int64(6), object(4)
memory usage: 233.7+ KB
None

In [ ]:
#라벨 인코딩
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()
train['Warehouse_block']=le.fit_transform(train['Warehouse_block'])
train['Mode_of_Shipment']=le.fit_transform(train['Mode_of_Shipment'])
train['Product_importance']=le.fit_transform(train['Product_importance'])
train['Gender']=le.fit_transform(train['Gender'])

le=LabelEncoder()
test['Warehouse_block']=le.fit_transform(test['Warehouse_block'])
test['Mode_of_Shipment']=le.fit_transform(test['Mode_of_Shipment'])
test['Product_importance']=le.fit_transform(test['Product_importance'])
test['Gender']=le.fit_transform(test['Gender'])

In [ ]:
print(train.info())
print(test.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8009 entries, 0 to 8008
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Warehouse_block      8009 non-null   int64
 1   Mode_of_Shipment     8009 non-null   int64
 2   Customer_care_calls  8009 non-null   int64
 3   Customer_rating      8009 non-null   int64
 4   Cost_of_the_Product  8009 non-null   int64
 5   Prior_purchases      8009 non-null   int64
 6   Product_importance   8009 non-null   int64
 7   Gender               8009 non-null   int64
 8   Discount_offered     8009 non-null   int64
 9   Weight_in_gms        8009 non-null   int64
 10  Reached.on.Time_Y.N  8009 non-null   int64
dtypes: int64(11)
memory usage: 688.4 KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2990 entries, 0 to 2989
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Warehouse_block      2990 non-null   int64
 1   Mode_of_Shipment     2990 non-null   int64
 2   Customer_care_calls  2990 non-null   int64
 3   Customer_rating      2990 non-null   int64
 4   Cost_of_the_Product  2990 non-null   int64
 5   Prior_purchases      2990 non-null   int64
 6   Product_importance   2990 non-null   int64
 7   Gender               2990 non-null   int64
 8   Discount_offered     2990 non-null   int64
 9   Weight_in_gms        2990 non-null   int64
dtypes: int64(10)
memory usage: 233.7 KB
None

In [ ]:
#트레이닝 데이터 분리
from sklearn.model_selection import train_test_split

X=train.drop(columns='Reached.on.Time_Y.N')
Y=train['Reached.on.Time_Y.N']

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=2024)

In [ ]:
#모델링 및 학습
from sklearn.ensemble import RandomForestClassifier

rfr = RandomForestClassifier(random_state=2024)
rfr.fit(X_train,Y_train)
pred=rfr.predict(X_test)

In [ ]:
#모델 평가

from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import f1_score

print(confusion_matrix(Y_test,pred))
print(accuracy_score(Y_test,pred))
print(recall_score(Y_test,pred))
print(precision_score(Y_test,pred))
print(f1_score(Y_test,pred))

[[388 187]
 [293 734]]
0.700374531835206
0.7147030185004869
0.7969598262757872
0.753593429158111

In [ ]:
#최종 결과 예측
pred2=rfr.predict_proba(test)
print(pred2)
pd.DataFrame({'ID':test_ID,'Reached.on.Time_Y.N':pred2[:,1]}).to_csv("result.csv",index=False)

data2=pd.read_csv("result.csv")
data2

[[0.43 0.57]
 [0.23 0.77]
 [0.65 0.35]
 ...
 [0.52 0.48]
 [0.31 0.69]
 [0.22 0.78]]

         ID  Reached.on.Time_Y.N
0      8010                 0.57
1      8011                 0.77
2      8012                 0.35
3      8013                 0.52
4      8014                 0.30
...     ...                  ...
2985  10995                 0.69
2986  10996                 0.63
2987  10997                 0.48
2988  10998                 0.69
2989  10999                 0.78

[2990 rows x 2 columns]